admin_actu:
    resource: "@AdminBundle/Controller/ActuController.php"
    type:     annotation

mtl_news:
    resource: "@MTLBundle/Controller/NewsController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@MTLBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
