admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@MTLBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
