admin_actu:
    resource: "@AdminBundle/Controller/actuController.php"
    type:     annotation
    prefix:

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

user:
    resource: "@MTLBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

contact:
    resource: "@AdminBundle/Form/actuType.php"
    type:     annotation
    prefix: